name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      short-sha: ${{ steps.vars.outputs.short_sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Lint code with flake8
        run: |
          pip install flake8
          flake8 app.py

      - name: Extract short SHA
        id: vars
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.short_sha }} .

      - name: Push Docker image
        run: docker push ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.short_sha }}

  test:
    needs: build-and-push
    runs-on: ubuntu-latest
    env:
      SHORT_SHA: ${{ needs.build-and-push.outputs.short-sha }}
      IMAGE_NAME: ${{_
