name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/app-flask
  IMAGE_TAG: ${{ github.sha }}

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout Code
      - uses: actions/checkout@v4

      # 2. Setup Python & Lint
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install flake8
      - run: flake8 .

      # 3. Build & Push Docker Image
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ env.IMAGE_NAME }}:latest

      # 4. Test Container Health
      - run: |
          docker run -d --name flask-test -p 5001:5000 ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          sleep 5
          curl -f http://localhost:5001/health
          docker stop flask-test

      # 5. Deploy to Kubernetes
      - uses: azure/setup-kubectl@v4
        with:
          version: 'latest'
      - run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config
          kubectl set image deployment/devops-flask devops-flask=${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} --record
          kubectl rollout status deployment/devops-flask
